global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'docura-spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Because Docker puts them on the same network, Prometheus can talk to it named 'backend'
      - targets: ['backend:8080']

